"""Update table

Revision ID: f6ae9d590d45
Revises: 194b7867b6ed
Create Date: 2026-01-24 11:39:45.387082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ae9d590d45'
down_revision: Union[str, Sequence[str], None] = '194b7867b6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stream_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('stream_url', sa.String(length=2048), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('last_frame_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_id'), 'streams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streams_id'), table_name='streams')
    op.drop_table('streams')
    # ### end Alembic commands ###
